### ISSUE TITLE
altair_widgets doesn’t work under altair 1.2 and ipywidgets 7.0

### ISSUE THREAD

**Issue by SPW1981** [altair-viz/altair_widgets#11]
When I launch altair_widgets (I tried the iris example posted here on github) I get the following error:
"TraitError: The 'x' trait of an Encoding instance must be a X, but a value of class 'NoneType' (i.e. None) was specified."

If I select an x encoding I get the same message for y and then for colour.After selecting 3 encodings, I get a visualization, but then I cannot modify anything anymore.

Any ideas?
Many thanks!

**Comment by stsievert** [comment]
I suspect this an issue with the new version of Altair and their upgrade to Vega-Lite 1.2. I would guess this issue would be resolved while using Altair 1.0.

**Comment by SPW1981** [comment]
Thanks for the pointers. I downgraded to altair 1.0 and the TraitError disappeared, but then I got an output of one mark_point without any interactive controls (so I couldn't do anything).
Finally I downgraded from ipywidgets-7.0.5 to ipywidgets-6.0 and now it works!
Many thanks for altair_widgets!

**Comment by stsievert** [comment]
I’ll add this to my todo list to fix.
