### ISSUE TITLE
Add unit tests & set-up Travis

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair_widgets#2]
To start with, we could just do smoke tests (i.e. run the main function and make sure it doesn't error). It might be worth investigating how ipywidgets tests things, to see if we can go a bit deeper.

**Comment by stsievert** [comment]
d48672bcb394183b6b67a62770ba05e391bc90d5 implements 7 basic tests in a Jupyter notebook. It runs some basic smoke screens and changes the encoding and ensures that the Altair encoding and the altair_widget encoding are the same given the same settings.

I integrated this with Travis and basic unit tests are implemented; I'm closing this issue now.
